name: Build and Push Image

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: web
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Dockerfile

      - name: Push To docker.studyum
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: docker.studyum.net
          username: likdan
          password: ${{ secrets.REGISTRY_PASSWORD }}

  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Connect and build and run on Aeza
        uses: appleboy/ssh-action@v0.1.3

        with:
          host: studyum.net
          username: root
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

          script: |
            curl https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/docker-compose.yml -o web/docker-compose.yml
            docker compose -f web/docker-compose.yml up -d
